-- Tabela aporte (espelho do Flyway da API).
create table aporte (
    id bigint generated by default as identity,
    investimento_id bigint        not null,
    valor           numeric(15,2) not null,
    data            date          not null,
    tipo            varchar(10)   not null,
    criado_em      timestamptz,
    criado_por     varchar(100),
    atualizado_em  timestamptz,
    atualizado_por varchar(100),
    uuid           uuid,
    versao         bigint not null default 0,
    deletado       boolean not null default false
);
