-- Tabela de auditoria de acesso (uma linha por requisicao HTTP).
create table auditoria (
    id              bigint generated by default as identity,
    usuario         varchar(100),
    metodo_http     varchar(10),
    endpoint        varchar(500),
    status_resposta integer,
    endereco_ip     varchar(45),
    data_hora       timestamptz
);
