-- Tabela categoria (espelho do Flyway da API).
create table categoria (
    id bigint generated by default as identity,
    nome             varchar(120) not null,
    tipo             varchar(20)  not null,
    categoria_pai_id bigint,
    cor              varchar(20),
    icone            varchar(40),
    ativa            boolean      not null default true,
    criado_em      timestamptz,
    criado_por     varchar(100),
    atualizado_em  timestamptz,
    atualizado_por varchar(100),
    uuid           uuid,
    versao         bigint not null default 0,
    deletado       boolean not null default false
);
