-- Tabela cotacao_produto (espelho do Flyway da API).
create table cotacao_produto (
    id bigint generated by default as identity,
    produto_id     bigint        not null,
    mercado_id     bigint        not null,
    preco_unitario numeric(15,2) not null,
    data           date          not null,
    origem         varchar(10)   not null,
    criado_em      timestamptz,
    criado_por     varchar(100),
    atualizado_em  timestamptz,
    atualizado_por varchar(100),
    uuid           uuid,
    versao         bigint not null default 0,
    deletado       boolean not null default false
);
