-- Tabela forma_pagamento (espelho do Flyway da API).
create table forma_pagamento (
    id bigint generated by default as identity,
    nome           varchar(120) not null,
    tipo           varchar(20)  not null,
    carteira_id    bigint,
    dia_fechamento smallint,
    dia_vencimento smallint,
    ativa          boolean      not null default true,
    criado_em      timestamptz,
    criado_por     varchar(100),
    atualizado_em  timestamptz,
    atualizado_por varchar(100),
    uuid           uuid,
    versao         bigint not null default 0,
    deletado       boolean not null default false
);
