-- Tabela investimento (espelho do Flyway da API).
create table investimento (
    id bigint generated by default as identity,
    nome              varchar(150) not null,
    tipo_investimento varchar(25)  not null,
    instituicao       varchar(120),
    carteira_id       bigint       not null,
    indexador         varchar(10),
    taxa_contratada   numeric(9,4),
    data_aplicacao    date         not null,
    data_vencimento   date,
    criado_em      timestamptz,
    criado_por     varchar(100),
    atualizado_em  timestamptz,
    atualizado_por varchar(100),
    uuid           uuid,
    versao         bigint not null default 0,
    deletado       boolean not null default false
);
