-- Tabela item_compra (espelho do Flyway da API).
create table item_compra (
    id bigint generated by default as identity,
    lista_compra_id      bigint        not null,
    produto_id           bigint        not null,
    quantidade           numeric(12,3) not null,
    unidade_medida_id    bigint,
    mercado_escolhido_id bigint,
    preco_unitario       numeric(15,2),
    comprado             boolean       not null default false,
    criado_em      timestamptz,
    criado_por     varchar(100),
    atualizado_em  timestamptz,
    atualizado_por varchar(100),
    uuid           uuid,
    versao         bigint not null default 0,
    deletado       boolean not null default false
);
