-- Tabela lista_compra (espelho do Flyway da API).
create table lista_compra (
    id bigint generated by default as identity,
    nome        varchar(150) not null,
    tipo        varchar(15)  not null,
    carteira_id bigint       not null,
    data        date         not null,
    status      varchar(10)  not null,
    criado_em      timestamptz,
    criado_por     varchar(100),
    atualizado_em  timestamptz,
    atualizado_por varchar(100),
    uuid           uuid,
    versao         bigint not null default 0,
    deletado       boolean not null default false
);
