-- Tabela mercado (espelho do Flyway da API).
create table mercado (
    id bigint generated by default as identity,
    nome     varchar(150) not null,
    tipo     varchar(20)  not null,
    endereco varchar(200),
    bairro   varchar(100),
    ativo    boolean      not null default true,
    criado_em      timestamptz,
    criado_por     varchar(100),
    atualizado_em  timestamptz,
    atualizado_por varchar(100),
    uuid           uuid,
    versao         bigint not null default 0,
    deletado       boolean not null default false
);
