-- Tabela parametro (espelho do Flyway da API).
create table parametro (
    id bigint generated by default as identity,
    chave           varchar(40)  not null,
    valor           numeric(9,4) not null,
    vigencia_inicio date         not null,
    descricao       varchar(200),
    criado_em      timestamptz,
    criado_por     varchar(100),
    atualizado_em  timestamptz,
    atualizado_por varchar(100),
    uuid           uuid,
    versao         bigint not null default 0,
    deletado       boolean not null default false
);
