-- Tabela participante_rateio (espelho do Flyway da API).
create table participante_rateio (
    id bigint generated by default as identity,
    rateio_id  bigint not null,
    usuario_id bigint not null,
    percentual numeric(7,4),
    valor      numeric(15,2),
    criado_em      timestamptz,
    criado_por     varchar(100),
    atualizado_em  timestamptz,
    atualizado_por varchar(100),
    uuid           uuid,
    versao         bigint not null default 0,
    deletado       boolean not null default false
);
