-- Tabela preferencia (espelho do Flyway da API).
create table preferencia (
    id bigint generated by default as identity,
    chave      varchar(40)  not null,
    valor      varchar(120) not null,
    usuario_id bigint,
    criado_em      timestamptz,
    criado_por     varchar(100),
    atualizado_em  timestamptz,
    atualizado_por varchar(100),
    uuid           uuid,
    versao         bigint not null default 0,
    deletado       boolean not null default false
);
