-- Tabela produto (espelho do Flyway da API).
create table produto (
    id bigint generated by default as identity,
    nome                     varchar(150) not null,
    descricao                varchar(300),
    categoria_id             bigint,
    unidade_medida_padrao_id bigint,
    codigo_barras            varchar(60),
    ativo                    boolean      not null default true,
    criado_em      timestamptz,
    criado_por     varchar(100),
    atualizado_em  timestamptz,
    atualizado_por varchar(100),
    uuid           uuid,
    versao         bigint not null default 0,
    deletado       boolean not null default false
);
