-- Tabela rateio (espelho do Flyway da API).
create table rateio (
    id bigint generated by default as identity,
    lancamento_id bigint      not null,
    tipo          varchar(15) not null,
    criado_em      timestamptz,
    criado_por     varchar(100),
    atualizado_em  timestamptz,
    atualizado_por varchar(100),
    uuid           uuid,
    versao         bigint not null default 0,
    deletado       boolean not null default false
);
