-- Tabela recorrencia (espelho do Flyway da API).
create table recorrencia (
    id bigint generated by default as identity,
    descricao          varchar(200)  not null,
    valor              numeric(15,2) not null,
    tipo               varchar(10)   not null,
    carteira_id        bigint        not null,
    categoria_id       bigint        not null,
    forma_pagamento_id bigint,
    frequencia         varchar(10)   not null,
    dia_vencimento     integer,
    data_inicio        date          not null,
    data_fim           date,
    ativa              boolean       not null default true,
    criado_em      timestamptz,
    criado_por     varchar(100),
    atualizado_em  timestamptz,
    atualizado_por varchar(100),
    uuid           uuid,
    versao         bigint not null default 0,
    deletado       boolean not null default false
);
