-- Tabela unidade_medida (espelho do Flyway da API).
create table unidade_medida (
    id bigint generated by default as identity,
    nome            varchar(60)  not null,
    sigla           varchar(10)  not null,
    tipo            varchar(20)  not null,
    fator_para_base numeric(12,6) not null default 1,
    criado_em      timestamptz,
    criado_por     varchar(100),
    atualizado_em  timestamptz,
    atualizado_por varchar(100),
    uuid           uuid,
    versao         bigint not null default 0,
    deletado       boolean not null default false
);
